### ISSUE TITLE
Arabic name issue

### ISSUE THREAD

**Issue by Abu-Khulzat** [amrbashir/hijri-widget#4]
Hi! 
Just installed your app and found it to be very nice. It is very simple and looks nice. 
Just want to mention that the name of the current month and I think the next (Jumada alUla and Jumada alAkhira) are not correct in Arabic. It should be 
جمادى الأولى not الأول
جمادى الأحرة (الثانية)

**Comment by amrbashir** [comment]
Thank you for reporting, I will fix it asap
